version: '2.1'
services:
  server:
    image: hastic/server:latest
    build:
      dockerfile: server/Dockerfile
      context: .
    environment:
      ZMQ_CONNECTION_STRING: ${ZMQ_CONNECTION_STRING:-tcp://analytics:8002}
      HASTIC_API_KEY: ${HASTIC_API_KEY}
      HASTIC_WEBHOOK_URL: ${HASTIC_WEBHOOK_URL}
      HASTIC_WEBHOOK_TYPE: ${HASTIC_WEBHOOK_TYPE}
      GRAFANA_URL: ${GRAFANA_URL}
      HASTIC_INSTANCE_NAME: ${HASTIC_INSTANCE_NAME}
      HASTIC_WEBHOOK_IMAGE: ${HASTIC_WEBHOOK_IMAGE}
      HASTIC_DB_CONNECTION_STRING: ${HASTIC_DB_CONNECTION_STRING}
      HASTIC_DB_CONNECTION_TYPE: ${HASTIC_DB_CONNECTION_TYPE}
      TIMEZONE_UTC_OFFSET: ${TIMEZONE_UTC_OFFSET}
    ports:
      - ${HASTIC_PORT:-8000}:8000
    volumes:
      - data-volume:/var/www/data
    restart: always

  analytics:
    image: hastic/analytics:latest
    build: analytics
    restart: always
    command: ${HASTIC_ANALYTICS_COMMAND}

volumes:
  data-volume:
